<a href="https://www.kaggle.com/code/alnwsany/movie-review-sentiment?scriptVersionId=155507885" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
!pip install tensorflow_datasets
#hi yahya put this code to sure that the package tensorflow-datasets that involve imdb reviews dataset in

In [2]:
import tensorflow_datasets as tfds

# Load the IMDB Reviews dataset
imdb, info = tfds.load("imdb_reviews", with_info=True, as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteAU91NH/imdb_reviews-train.tfrecord…

Generating test examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteAU91NH/imdb_reviews-test.tfrecord*…

Generating unsupervised examples...:   0%|          | 0/50000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteAU91NH/imdb_reviews-unsupervised.t…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [3]:
print(info)  # show all the info about the imdb review dataset

tfds.core.DatasetInfo(
    name='imdb_reviews',
    full_name='imdb_reviews/plain_text/1.0.0',
    description="""
    Large Movie Review Dataset. This is a dataset for binary sentiment
    classification containing substantially more data than previous benchmark
    datasets. We provide a set of 25,000 highly polar movie reviews for training,
    and 25,000 for testing. There is additional unlabeled data for use as well.
    """,
    config_description="""
    Plain text
    """,
    homepage='http://ai.stanford.edu/~amaas/data/sentiment/',
    data_path=PosixGPath('/tmp/tmpb65ggvw_tfds'),
    file_format=tfrecord,
    download_size=80.23 MiB,
    dataset_size=129.83 MiB,
    features=FeaturesDict({
        'label': ClassLabel(shape=(), dtype=int64, num_classes=2),
        'text': Text(shape=(), dtype=string),
    }),
    supervised_keys=('text', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=25000, num_shards=1>,
        'train': <SplitInf

In [4]:
# Print the contents of the dataset you downloaded
print(imdb)

{Split('train'): <_PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>, Split('test'): <_PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>, Split('unsupervised'): <_PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>}


In [5]:
# Take 2 training examples and print its contents  - this will out examples of movie reviews 
for example in imdb['train'].take(2):
  print(f'\n{example}')


(<tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">, <tf.Tensor: shape=(), dtype=int64, numpy=0>)

(<tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable 

**now we going to split our dataset that include train and test 
using numpy**

In [6]:
import numpy as np

# Get the train and test sets
train_data, test_data = imdb['train'], imdb['test']

# Initialize sentences and labels lists
training_sentences = []
training_labels = []

testing_sentences = []
testing_labels = []

# Loop over all training examples and save the sentences and labels
for s,l in train_data:
  training_sentences.append(s.numpy().decode('utf8'))
  training_labels.append(l.numpy())

# Loop over all test examples and save the sentences and labels
for s,l in test_data:
  testing_sentences.append(s.numpy().decode('utf8'))
  testing_labels.append(l.numpy())

# Convert labels lists to numpy array
training_labels_final = np.array(training_labels)
testing_labels_final = np.array(testing_labels)

In [7]:
# yahya showing example movie review after split the data 
testing_sentences[0]

"There are films that make careers. For George Romero, it was NIGHT OF THE LIVING DEAD; for Kevin Smith, CLERKS; for Robert Rodriguez, EL MARIACHI. Add to that list Onur Tukel's absolutely amazing DING-A-LING-LESS. Flawless film-making, and as assured and as professional as any of the aforementioned movies. I haven't laughed this hard since I saw THE FULL MONTY. (And, even then, I don't think I laughed quite this hard... So to speak.) Tukel's talent is considerable: DING-A-LING-LESS is so chock full of double entendres that one would have to sit down with a copy of this script and do a line-by-line examination of it to fully appreciate the, uh, breadth and width of it. Every shot is beautifully composed (a clear sign of a sure-handed director), and the performances all around are solid (there's none of the over-the-top scenery chewing one might've expected from a film like this). DING-A-LING-LESS is a film whose time has come."

In [8]:
# yahya showing example movie review label after split the data for the same instance up ⤴️
testing_labels[0]

1

In [9]:
# Parameters for the proccess of tokenization and padd sequence the data
#this step prepare the data for the fit and training

vocab_size = 10000
max_length = 120
embedding_dim = 16
trunc_type='post'
oov_tok = "<OOV>"

**ok as describe for the next step the concept of our program it's make the pc or the device understand the human langauge so we try to convert the text to numerical for make the hardware understand the setence and to be easy to deal with so we convet the long reviews to small sentences or just words and this porccess called tokenization after that we deal with words as sequence**

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Initialize the Tokenizer class
tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)

# Generate the word index dictionary for the training sentences
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

# Generate and pad the training sequences
sequences = tokenizer.texts_to_sequences(training_sentences)
padded = pad_sequences(sequences,maxlen=max_length, truncating=trunc_type)

# Generate and pad the test sequences
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences,maxlen=max_length, truncating=trunc_type)

In [11]:
## yahya showing example movie review after padded
testing_padded[0]

array([  48,   24,  106,   13,   95, 4066,   16,  740, 5065,   10,   14,
        312,    5,    2,  579,  349,   16, 1847, 1257,    1,   16,  668,
       7666, 5531,    1,  761,    6,   13, 1026,    1,    1,  425,  478,
          1,    4,    1,  327, 3560,   20,  229,    3,   15, 5742,    3,
         15, 1620,   15,   99,    5,    2, 3550,  100,   11,  772, 1498,
         12,  252,  235,   11,  217,    2,  366, 6454,    3,   58,   93,
         11,   90,  102,   11, 1498,  177,   12,  252,   36,    6, 1126,
          1,  674,    7, 4387,    1,    4,    1,  327,    7,   36, 8300,
        366,    5, 1403,    1,   13,   29,   60,   26,    6,  867,  178,
         17,    4, 1037,    5,   12,  227,    3,   79,    4,  345,   32,
        345, 5159,    5,   10,    6, 1314, 1143,    2, 5619,    1],
      dtype=int32)

**ok let's build the model i'll build a sample model to acheive best perfomence...i hope !**

In [12]:
import tensorflow as tf

# Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Setup the training parameters
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# Print the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 120, 16)           160000    
                                                                 
 flatten (Flatten)           (None, 1920)              0         
                                                                 
 dense (Dense)               (None, 6)                 11526     
                                                                 
 dense_1 (Dense)             (None, 1)                 7         
                                                                 
Total params: 171533 (670.05 KB)
Trainable params: 171533 (670.05 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


**wonderful every thing gona be ok after that we need to train/fit our model and this the next step****  **

In [13]:
num_epochs = 10 #the number of iterations that model will do to try to under stand the relation between label and sentence to genrate knowledge 

# Train the model
model.fit(padded,
          training_labels_final,
          epochs=num_epochs,
          validation_data=(testing_padded, testing_labels_final))

Epoch 1/10
782/782 [==============================] - 4s 5ms/step - loss: 0.4967 - accuracy: 0.7367 - val_loss: 0.3786 - val_accuracy: 0.8308
Epoch 2/10
782/782 [==============================] - 4s 5ms/step - loss: 0.2427 - accuracy: 0.9041 - val_loss: 0.4057 - val_accuracy: 0.8239
Epoch 3/10
782/782 [==============================] - 3s 4ms/step - loss: 0.0984 - accuracy: 0.9727 - val_loss: 0.4993 - val_accuracy: 0.8112
Epoch 4/10
782/782 [==============================] - 3s 4ms/step - loss: 0.0253 - accuracy: 0.9966 - val_loss: 0.5934 - val_accuracy: 0.8085
Epoch 5/10
782/782 [==============================] - 3s 4ms/step - loss: 0.0065 - accuracy: 0.9995 - val_loss: 0.6757 - val_accuracy: 0.8077
Epoch 6/10
782/782 [==============================] - 3s 4ms/step - loss: 0.0020 - accuracy: 0.9999 - val_loss: 0.7418 - val_accuracy: 0.8072
Epoch 7/10
782/782 [==============================] - 4s 4ms/step - loss: 9.1297e-04 - accuracy: 1.0000 - val_loss: 0.7880 - val_accuracy: 0.8084
Ep

In [14]:
# the coming it's info about the model we build 
# Get the embedding layer from the model (i.e. first layer)
embedding_layer = model.layers[0]

# Get the weights of the embedding layer
embedding_weights = embedding_layer.get_weights()[0]

# Print the shape. Expected is (vocab_size, embedding_dim)
print(embedding_weights.shape)

(10000, 16)


**yeah amazing we reached to here so let's test our programme #
you can input any review u want and see the result**

In [15]:
#you can edit this to any review you want
new_review = ['this was amazing movie i really enjoy it']


In [16]:


# Tokenize and pad the new review
new_sequences = tokenizer.texts_to_sequences(new_review)
new_padded = pad_sequences(new_sequences, maxlen=max_length, truncating=trunc_type)
print(new_review)

# Make a prediction using the trained model
prediction = model.predict(new_padded)
if prediction[0] > 0.5 :
    print('\n positive review⭐')
else:
     print('\n negative review😑')


['this was amazing movie i really enjoy it']
1/1 [==============================] - 0s 89ms/step

 positive review⭐
